'use client'

import { useEffect, useState } from 'react'
import { supabase } from '@/lib/supabase'
import type { Settings } from '@/types'
import { toast } from 'sonner'
import { Eye, EyeOff, KeyRound, Save, UserPlus } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'

export default function SettingsPage() {
  const [settings, setSettings] = useState<Partial<Settings>>({
    company_name: 'Bindu Premium',
    generated_by: 'Nahid',
    payment_by: '',
  })
  const [saving, setSaving] = useState(false)

  // Change password
  const [newPassword, setNewPassword] = useState('')
  const [confirmPassword, setConfirmPassword] = useState('')
  const [showNewPw, setShowNewPw] = useState(false)
  const [changingPw, setChangingPw] = useState(false)

  // Add admin
  const [adminEmail, setAdminEmail] = useState('')
  const [adminPassword, setAdminPassword] = useState('')
  const [showAdminPw, setShowAdminPw] = useState(false)
  const [addingAdmin, setAddingAdmin] = useState(false)

  useEffect(() => {
    supabase.from('settings').select('*').limit(1).single().then(({ data }) => {
      if (data) setSettings(data as Settings)
    })
  }, [])

  async function save() {
    setSaving(true)
    const payload = {
      company_name: settings.company_name,
      generated_by: settings.generated_by,
      payment_by: settings.payment_by,
      updated_at: new Date().toISOString(),
    }
    let error
    if (settings.id) {
      ({ error } = await supabase.from('settings').update(payload).eq('id', settings.id))
    } else {
      const res = await supabase.from('settings').insert(payload).select().single()
      error = res.error
      if (res.data) setSettings(res.data as Settings)
    }
    if (error) toast.error(error.message)
    else toast.success('Settings saved')
    setSaving(false)
  }

  async function changePassword(e: React.FormEvent) {
    e.preventDefault()
    if (newPassword !== confirmPassword) { toast.error('Passwords do not match'); return }
    if (newPassword.length < 6) { toast.error('Password must be at least 6 characters'); return }
    setChangingPw(true)
    const { error } = await supabase.auth.updateUser({ password: newPassword })
    if (error) toast.error(error.message)
    else { toast.success('Password updated'); setNewPassword(''); setConfirmPassword('') }
    setChangingPw(false)
  }

  async function addAdmin(e: React.FormEvent) {
    e.preventDefault()
    if (adminPassword.length < 6) { toast.error('Password must be at least 6 characters'); return }
    setAddingAdmin(true)
    const res = await fetch('/api/admin', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ email: adminEmail, password: adminPassword }),
    })
    const data = await res.json()
    if (!res.ok) toast.error(data.error)
    else { toast.success(`Admin ${data.email} created`); setAdminEmail(''); setAdminPassword('') }
    setAddingAdmin(false)
  }

  return (
    <div className="p-4 sm:p-6 lg:p-8 max-w-lg mx-auto">
      <div className="mb-4 sm:mb-6">
        <h1 className="text-xl sm:text-2xl font-bold text-gray-900">Settings</h1>
        <p className="text-gray-500 text-sm mt-0.5">Company details and signature names on salary slips</p>
      </div>

      <div className="bg-white rounded-xl border border-gray-200 p-6 space-y-5">
        <div>
          <Label>Company Name</Label>
          <Input value={settings.company_name ?? ''} onChange={e => setSettings(p => ({ ...p, company_name: e.target.value }))} className="mt-1" />
        </div>
        <div>
          <Label>Salary Generated By (name on slip)</Label>
          <Input value={settings.generated_by ?? ''} onChange={e => setSettings(p => ({ ...p, generated_by: e.target.value }))} className="mt-1" placeholder="e.g. Nahid" />
        </div>
        <div>
          <Label>Payment By (name on slip)</Label>
          <Input value={settings.payment_by ?? ''} onChange={e => setSettings(p => ({ ...p, payment_by: e.target.value }))} className="mt-1" placeholder="e.g. Manager name" />
        </div>

        <div className="pt-2">
          <Button onClick={save} disabled={saving} className="gap-2 w-full">
            <Save size={15} />{saving ? 'Saving…' : 'Save Settings'}
          </Button>
        </div>
      </div>

      {/* Change Password */}
      <div className="mt-6 bg-white rounded-xl border border-gray-200 p-6">
        <div className="flex items-center gap-2 mb-4">
          <KeyRound size={16} className="text-gray-500" />
          <h2 className="font-semibold text-gray-800">Change Password</h2>
        </div>
        <form onSubmit={changePassword} className="space-y-4">
          <div>
            <Label>New Password</Label>
            <div className="relative mt-1">
              <Input
                type={showNewPw ? 'text' : 'password'}
                value={newPassword}
                onChange={e => setNewPassword(e.target.value)}
                placeholder="Min. 6 characters"
                className="pr-10"
                required
              />
              <button type="button" onClick={() => setShowNewPw(p => !p)} tabIndex={-1}
                className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-600">
                {showNewPw ? <EyeOff size={15} /> : <Eye size={15} />}
              </button>
            </div>
          </div>
          <div>
            <Label>Confirm Password</Label>
            <div className="relative mt-1">
              <Input
                type={showNewPw ? 'text' : 'password'}
                value={confirmPassword}
                onChange={e => setConfirmPassword(e.target.value)}
                placeholder="Re-enter new password"
                className="pr-10"
                required
              />
            </div>
          </div>
          <Button type="submit" disabled={changingPw} className="w-full gap-2">
            <KeyRound size={14} />{changingPw ? 'Updating…' : 'Update Password'}
          </Button>
        </form>
      </div>

      {/* Add Admin */}
      <div className="mt-4 bg-white rounded-xl border border-gray-200 p-6">
        <div className="flex items-center gap-2 mb-4">
          <UserPlus size={16} className="text-gray-500" />
          <h2 className="font-semibold text-gray-800">Add Admin</h2>
        </div>
        <form onSubmit={addAdmin} className="space-y-4">
          <div>
            <Label>Email</Label>
            <Input
              type="email"
              value={adminEmail}
              onChange={e => setAdminEmail(e.target.value)}
              placeholder="newadmin@bindupremium.com"
              className="mt-1"
              required
            />
          </div>
          <div>
            <Label>Temporary Password</Label>
            <div className="relative mt-1">
              <Input
                type={showAdminPw ? 'text' : 'password'}
                value={adminPassword}
                onChange={e => setAdminPassword(e.target.value)}
                placeholder="Min. 6 characters"
                className="pr-10"
                required
              />
              <button type="button" onClick={() => setShowAdminPw(p => !p)} tabIndex={-1}
                className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-600">
                {showAdminPw ? <EyeOff size={15} /> : <Eye size={15} />}
              </button>
            </div>
          </div>
          <Button type="submit" disabled={addingAdmin} className="w-full gap-2">
            <UserPlus size={14} />{addingAdmin ? 'Creating…' : 'Create Admin'}
          </Button>
        </form>
      </div>

      <div className="mt-6 bg-blue-50 border border-blue-200 rounded-lg p-4 text-sm text-blue-800">
        <p className="font-semibold mb-1">Salary Rules (fixed)</p>
        <ul className="space-y-1 text-blue-700 text-xs">
          <li>• Working days per month: <strong>26</strong></li>
          <li>• Daily rate: Basic Salary ÷ 26</li>
          <li>• Leave deduction: only days beyond yearly allowance</li>
          <li>• Late deduction: every 3 late days = 1 day salary cut</li>
          <li>• OT: 1 OT day = 1 full day salary (Basic ÷ 26)</li>
          <li>• Default conveyance: <strong>৳ 1,500/month</strong></li>
        </ul>
      </div>
    </div>
  )
}
