'use client'

import { useEffect, useState } from 'react'
import { supabase } from '@/lib/supabase'
import type { Settings } from '@/types'
import { toast } from 'sonner'
import { Save } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'

export default function SettingsPage() {
  const [settings, setSettings] = useState<Partial<Settings>>({
    company_name: 'Bindu Premium',
    generated_by: 'Nahid',
    payment_by: '',
  })
  const [saving, setSaving] = useState(false)

  useEffect(() => {
    supabase.from('settings').select('*').limit(1).single().then(({ data }) => {
      if (data) setSettings(data as Settings)
    })
  }, [])

  async function save() {
    setSaving(true)
    const payload = {
      company_name: settings.company_name,
      generated_by: settings.generated_by,
      payment_by: settings.payment_by,
      updated_at: new Date().toISOString(),
    }
    let error
    if (settings.id) {
      ({ error } = await supabase.from('settings').update(payload).eq('id', settings.id))
    } else {
      const res = await supabase.from('settings').insert(payload).select().single()
      error = res.error
      if (res.data) setSettings(res.data as Settings)
    }
    if (error) toast.error(error.message)
    else toast.success('Settings saved')
    setSaving(false)
  }

  return (
    <div className="p-8 max-w-lg mx-auto">
      <div className="mb-6">
        <h1 className="text-2xl font-bold text-gray-900">Settings</h1>
        <p className="text-gray-500 text-sm mt-0.5">Company details and signature names on salary slips</p>
      </div>

      <div className="bg-white rounded-xl border border-gray-200 p-6 space-y-5">
        <div>
          <Label>Company Name</Label>
          <Input value={settings.company_name ?? ''} onChange={e => setSettings(p => ({ ...p, company_name: e.target.value }))} className="mt-1" />
        </div>
        <div>
          <Label>Salary Generated By (name on slip)</Label>
          <Input value={settings.generated_by ?? ''} onChange={e => setSettings(p => ({ ...p, generated_by: e.target.value }))} className="mt-1" placeholder="e.g. Nahid" />
        </div>
        <div>
          <Label>Payment By (name on slip)</Label>
          <Input value={settings.payment_by ?? ''} onChange={e => setSettings(p => ({ ...p, payment_by: e.target.value }))} className="mt-1" placeholder="e.g. Manager name" />
        </div>

        <div className="pt-2">
          <Button onClick={save} disabled={saving} className="gap-2 w-full">
            <Save size={15} />{saving ? 'Saving…' : 'Save Settings'}
          </Button>
        </div>
      </div>

      <div className="mt-6 bg-blue-50 border border-blue-200 rounded-lg p-4 text-sm text-blue-800">
        <p className="font-semibold mb-1">Salary Rules (fixed)</p>
        <ul className="space-y-1 text-blue-700 text-xs">
          <li>• Working days per month: <strong>26</strong></li>
          <li>• Daily rate: Basic Salary ÷ 26</li>
          <li>• Leave deduction: only days beyond yearly allowance</li>
          <li>• Late deduction: every 3 late days = 1 day salary cut</li>
          <li>• OT: 1 OT day = 1 full day salary (Basic ÷ 26)</li>
          <li>• Default conveyance: <strong>৳ 1,500/month</strong></li>
        </ul>
      </div>
    </div>
  )
}
